//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revistas
    {
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string CodigoBarra { get; set; }
        public System.DateTime FechaCirculacion { get; set; }
        public double Precio { get; set; }
    }
}
